name: 'news_anchor'
version: 0.0.1
description: News Aggregation and Content Curation (MSc Project)
author: Rafael Alves Sa <ec13293@qmul.ac.uk>
dependencies:
  appengine: '>=0.3.0+1'
  browser: '>=0.10.0+2'
  core_elements: '>=0.7.1+2'
  crypto: '>=0.9.0'
  dart_feed: '>=0.0.4'
  html: '>=0.12.1+2'
  intl: '0.12.4+1'
  paper_elements: '>=0.7.1+1'
  polymer: '>=0.16.3+3'
  sqljocky: '>=0.11.0'
transformers:
- polymer:
    entry_points:
      - web/index.html
